import './js/header';
import './js/exercises-aside';
import './js/exercises-main';
import './js/favorites';
import './js/footer';
import './js/loader';
import './js/scroll-down';
import '../src/js/api/api';
import './js/api-service/exercises-api';
import './js/api-service/categories-api';
import './js/templates/exercises-markup';
import './js/exercises';
import './js/exercises-category.js'
import './js/templates/exercises-category-markup.js';
import './js/scroll-up';